version: 2.1
orbs:
  terraform: circleci/terraform@1.2.1
workflows:
  deploy_ec2_infra:
    jobs:
    - terraform/validate:
        checkout: true
        context: terraform
    - terraform/plan:
        checkout: true
        context: terraform
        persistent-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: main
        requires:
          - terraform/plan